name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Create or Update `gh-pages` Branch
        run: |
          git fetch origin gh-pages || true
          git checkout gh-pages || git checkout -b gh-pages
          git rm -rf .
          cp -r .gitignore index.html *.css *.js . # Adjust this line based on the actual files in your repo
          git add .
          git commit -m "Deploy to GitHub Pages" || echo "No changes to commit"
          git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
