name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Deploy
        env:
          ARENA_API_TOKEN: ${{ secrets.ARENA_API_TOKEN }}
        run: |
          echo "Building site..."
          echo "const arenaToken = '${ARENA_API_TOKEN}';" > env.js
          # Your build and deploy commands here
          npm install
          npm run build
