name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Create or Update `gh-pages` Branch
        run: |
          # Create a temporary directory to work with
          mkdir gh-pages
          cd gh-pages

          # Initialize a Git repository
          git init
          git remote add origin https://github.com/${{ github.repository }}.git

          # Fetch the existing gh-pages branch or create it if it does not exist
          git fetch origin gh-pages || echo "No gh-pages branch found, creating new one."
          git checkout gh-pages || git checkout -b gh-pages

          # Remove all files from the gh-pages branch
          git rm -rf .

          # Copy files from the main branch to gh-pages
          cp -r ../* .

          # Add and commit the files
          git add .
          git commit -m "Deploy to GitHub Pages" || echo "No changes to commit"

          # Push changes to the gh-pages branch
          git push --force origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
