name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Create or Update `gh-pages` Branch
        run: |
          # Create a temporary directory
          mkdir gh-pages
          
          # Move to the temporary directory
          cd gh-pages
          
          # Initialize a new Git repository
          git init
          git remote add origin https://github.com/${{ github.repository }}.git

          # Fetch the gh-pages branch if it exists
          git fetch origin gh-pages || echo "No gh-pages branch found, creating new one."
          
          # Check out the gh-pages branch or create it
          git checkout gh-pages || git checkout -b gh-pages

          # Copy files from the main branch
          cp -r ../* . # Copy files from the root of the main branch

          # Commit and push changes
          git add .
          git commit -m "Deploy to GitHub Pages" || echo "No changes to commit"
          git push --force origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
